// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Web_KB.Data;

#nullable disable

namespace Web_KB.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.HasSequence("UtilisateursSequence");

            modelBuilder.Entity("Web_KB.Entity.Candidature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CandidatiId")
                        .HasColumnType("int");

                    b.Property<int>("CreerPar")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateSoumission")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateSupperission")
                        .HasColumnType("datetime2");

                    b.Property<bool>("EstSupprime")
                        .HasColumnType("bit");

                    b.Property<string>("MessageMotivation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OffreEmploiId")
                        .HasColumnType("int");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SupperimerPar")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CandidatiId");

                    b.HasIndex("OffreEmploiId");

                    b.ToTable("Candidature", (string)null);
                });

            modelBuilder.Entity("Web_KB.Entity.Commentaire", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Contenu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CreerPar")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCommentaire")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateSupperission")
                        .HasColumnType("datetime2");

                    b.Property<bool>("EstSupprime")
                        .HasColumnType("bit");

                    b.Property<int>("PublicationId")
                        .HasColumnType("int");

                    b.Property<int?>("SupperimerPar")
                        .HasColumnType("int");

                    b.Property<int>("UtilisateursId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PublicationId");

                    b.HasIndex("UtilisateursId");

                    b.ToTable("Commentaire");
                });

            modelBuilder.Entity("Web_KB.Entity.Competence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CandidatiId")
                        .HasColumnType("int");

                    b.Property<int>("CreerPar")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateSupperission")
                        .HasColumnType("datetime2");

                    b.Property<bool>("EstSupprime")
                        .HasColumnType("bit");

                    b.Property<int>("Niveau")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SupperimerPar")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CandidatiId");

                    b.ToTable("Competence");
                });

            modelBuilder.Entity("Web_KB.Entity.Entreprise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreerPar")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateSupperission")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EstSupprime")
                        .HasColumnType("bit");

                    b.Property<string>("Logo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Secteur")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SupperimerPar")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Entreprise");
                });

            modelBuilder.Entity("Web_KB.Entity.Formation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CandidatiId")
                        .HasColumnType("int");

                    b.Property<int>("CreerPar")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateSupperission")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Diplome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ecole")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EstSupprime")
                        .HasColumnType("bit");

                    b.Property<int?>("SupperimerPar")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CandidatiId");

                    b.ToTable("Formation");
                });

            modelBuilder.Entity("Web_KB.Entity.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Contenu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CreerPar")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateEnvoie")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateSupperission")
                        .HasColumnType("datetime2");

                    b.Property<int>("DestinataireId")
                        .HasColumnType("int");

                    b.Property<bool>("EstSupprime")
                        .HasColumnType("bit");

                    b.Property<int>("ExpediteurId")
                        .HasColumnType("int");

                    b.Property<int?>("SupperimerPar")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DestinataireId");

                    b.HasIndex("ExpediteurId");

                    b.ToTable("Message");
                });

            modelBuilder.Entity("Web_KB.Entity.OffreEmploi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreerPar")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatePublication")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateSupperission")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EntrepriseId")
                        .HasColumnType("int");

                    b.Property<bool>("EstSupprime")
                        .HasColumnType("bit");

                    b.Property<string>("Lieu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Salaire")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SupperimerPar")
                        .HasColumnType("int");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeContrat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EntrepriseId");

                    b.ToTable("OffreEmploi");
                });

            modelBuilder.Entity("Web_KB.Entity.Publication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Contenu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CreerPar")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatePublication")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateSupperission")
                        .HasColumnType("datetime2");

                    b.Property<bool>("EstSupprime")
                        .HasColumnType("bit");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SupperimerPar")
                        .HasColumnType("int");

                    b.Property<int>("UtilisateursId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UtilisateursId");

                    b.ToTable("Publication");
                });

            modelBuilder.Entity("Web_KB.Entity.Utilisateurs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("NEXT VALUE FOR [UtilisateursSequence]");

                    SqlServerPropertyBuilderExtensions.UseSequence(b.Property<int>("Id"));

                    b.Property<int>("CreerPar")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateInscription")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateSupperission")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EstSupprime")
                        .HasColumnType("bit");

                    b.Property<string>("MotDePasse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoProfil")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SupperimerPar")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Utilisateur", (string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("Web_KB.Entity.Candidat", b =>
                {
                    b.HasBaseType("Web_KB.Entity.Utilisateurs");

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitreProfil")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Candidat", (string)null);
                });

            modelBuilder.Entity("Web_KB.Entity.Recruteur", b =>
                {
                    b.HasBaseType("Web_KB.Entity.Utilisateurs");

                    b.Property<int?>("EntrepriseId")
                        .HasColumnType("int");

                    b.HasIndex("EntrepriseId");

                    b.ToTable("Recruteur");
                });

            modelBuilder.Entity("Web_KB.Entity.Candidature", b =>
                {
                    b.HasOne("Web_KB.Entity.Candidat", "Candidat")
                        .WithMany("Candidature")
                        .HasForeignKey("CandidatiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Web_KB.Entity.OffreEmploi", "OffreEmploi")
                        .WithMany("Candidature")
                        .HasForeignKey("OffreEmploiId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Candidat");

                    b.Navigation("OffreEmploi");
                });

            modelBuilder.Entity("Web_KB.Entity.Commentaire", b =>
                {
                    b.HasOne("Web_KB.Entity.Publication", "Publication")
                        .WithMany("Commentaire")
                        .HasForeignKey("PublicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Web_KB.Entity.Utilisateurs", "Utilisateurs")
                        .WithMany("Commentaire")
                        .HasForeignKey("UtilisateursId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Publication");

                    b.Navigation("Utilisateurs");
                });

            modelBuilder.Entity("Web_KB.Entity.Competence", b =>
                {
                    b.HasOne("Web_KB.Entity.Candidat", "Candidat")
                        .WithMany("Competence")
                        .HasForeignKey("CandidatiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidat");
                });

            modelBuilder.Entity("Web_KB.Entity.Formation", b =>
                {
                    b.HasOne("Web_KB.Entity.Candidat", "Candidat")
                        .WithMany("Formation")
                        .HasForeignKey("CandidatiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidat");
                });

            modelBuilder.Entity("Web_KB.Entity.Message", b =>
                {
                    b.HasOne("Web_KB.Entity.Utilisateurs", "Destinataire")
                        .WithMany("MessagesRecus")
                        .HasForeignKey("DestinataireId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Web_KB.Entity.Utilisateurs", "Expediteur")
                        .WithMany("MessagesEnvoyes")
                        .HasForeignKey("ExpediteurId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Destinataire");

                    b.Navigation("Expediteur");
                });

            modelBuilder.Entity("Web_KB.Entity.OffreEmploi", b =>
                {
                    b.HasOne("Web_KB.Entity.Entreprise", "Entreprise")
                        .WithMany("OffreEmplois")
                        .HasForeignKey("EntrepriseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entreprise");
                });

            modelBuilder.Entity("Web_KB.Entity.Publication", b =>
                {
                    b.HasOne("Web_KB.Entity.Utilisateurs", "Utilisateurs")
                        .WithMany("Publication")
                        .HasForeignKey("UtilisateursId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilisateurs");
                });

            modelBuilder.Entity("Web_KB.Entity.Recruteur", b =>
                {
                    b.HasOne("Web_KB.Entity.Entreprise", "Entreprise")
                        .WithMany("Recruteurs")
                        .HasForeignKey("EntrepriseId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Entreprise");
                });

            modelBuilder.Entity("Web_KB.Entity.Entreprise", b =>
                {
                    b.Navigation("OffreEmplois");

                    b.Navigation("Recruteurs");
                });

            modelBuilder.Entity("Web_KB.Entity.OffreEmploi", b =>
                {
                    b.Navigation("Candidature");
                });

            modelBuilder.Entity("Web_KB.Entity.Publication", b =>
                {
                    b.Navigation("Commentaire");
                });

            modelBuilder.Entity("Web_KB.Entity.Utilisateurs", b =>
                {
                    b.Navigation("Commentaire");

                    b.Navigation("MessagesEnvoyes");

                    b.Navigation("MessagesRecus");

                    b.Navigation("Publication");
                });

            modelBuilder.Entity("Web_KB.Entity.Candidat", b =>
                {
                    b.Navigation("Candidature");

                    b.Navigation("Competence");

                    b.Navigation("Formation");
                });
#pragma warning restore 612, 618
        }
    }
}
